[project]
name = "secretsdk"
revision = "1.0"
require_reason = false

[profiles.default]
DATABASE_URL = { description = "Database connection string", required = true }

[profiles.development]
DATABASE_URL = { default = "testing dev" }

[profiles.production]
DATABASE_URL = { default = "testing prod" }